dist: trusty
sudo: require

language:
  - c

copiler: gcc

addons:
  apt:
    packages:
      - gcc-6
      - g++-6
      - cmake


script:
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-6
  - export CXX=/usr/bin/g++-6
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  - cmake --build ./build --config Debug --target clean --
  - cmake --build ./build --config Debug --target all -- -j 10
  - ./build/bin/yalex_tests_app